#!/bin/bash
# Bootstrap script for secrets provisioning
# Prompts user for sensitive values and creates .env file
# Usage: ./bootstrap/04-setup-secrets.sh

set -euo pipefail

# Set default compose directory
COMPOSE_DIR="${COMPOSE_DIR:-/opt/infra/compose}"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "Enforcer Secrets Provisioning Bootstrap"
echo "=========================================="
echo ""

# Prompt for PostgreSQL password
echo "Please provide the following secrets:"
echo ""
read -rp "PostgreSQL password: " POSTGRES_PASSWORD
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  echo -e "${RED}Error: PostgreSQL password cannot be empty${NC}"
  exit 1
fi
echo ""

# Prompt for domain name
read -rp "Domain name (e.g., enforcer.example.com): " DOMAIN
if [[ -z "$DOMAIN" ]]; then
  echo -e "${RED}Error: Domain name cannot be empty${NC}"
  exit 1
fi
echo ""

# Ensure compose directory exists
if [[ ! -d "$COMPOSE_DIR" ]]; then
  echo "Creating compose directory: $COMPOSE_DIR"
  mkdir -p "$COMPOSE_DIR"
fi

# Create .env file
ENV_FILE="$COMPOSE_DIR/.env"

cat > "$ENV_FILE" << EOF
# Shared infrastructure secrets
# Generated by setup-secrets.sh — do not commit to git

# PostgreSQL
POSTGRES_USER=enforcer
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Domain
DOMAIN=$DOMAIN

# Enforcer backend
DATABASE_URL=postgresql://enforcer:$POSTGRES_PASSWORD@postgres:5432/enforcer_dev
NODE_ENV=production
PORT=3001
EOF

# Set restrictive permissions
chmod 600 "$ENV_FILE"

echo -e "${GREEN}✓ Secrets file created successfully${NC}"
echo ""
echo "File location: $ENV_FILE"
echo "Permissions: $(stat -c '%a' "$ENV_FILE")"
echo ""
echo -e "${YELLOW}IMPORTANT: GitHub Actions Secrets${NC}"
echo "The following secrets must be set in your GitHub repository settings:"
echo "  • DEPLOY_SSH_KEY"
echo "  • VPS_HOST"
echo "  • VPS_USER"
echo "  • POSTGRES_PASSWORD"
echo "  • DOMAIN"
echo ""
echo "See: https://github.com/<owner>/<repo>/settings/secrets/actions"
echo ""
